# Start on boot
exec-once = bash $HOME/.config/Scripts/random_wall_on_home.sh
exec-once = mako
exec-once = alacritty
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store
exec-once = kdeconnectd
# exec-once = waybar -c $HOME/.config/waybar/MangoWC/config.jsonc -s $HOME/.config/waybar/style.css
# exec-once = swayidle -w timeout 300 'systemctl suspend' before-sleep 'hyprlock'
