# Overview settings
enable_hotarea=1
hotarea_size=10
hotarea_corner=0
overviewgappi=10
overviewgappo=200

# Keyboard related
repeat_rate=60
repeat_delay=200
numlockon=0
xkb_rules_layout=us

# Touchpad settings
trackpad_natural_scrolling=1
accel_speed=1
accel_profile=2
axis_scroll_factor=2.0
cursor_theme=Bibata-Modern-Ice
cursor_size=24
warpcursor=1
focus_on_activate=1
sloppyfocus=1

gappih=5
gappiv=5
gappoh=10
gappov=10
borderpx=4
border_radius=24
no_border_when_single=1
focuscolor=0xffffffff
bordercolor=0x44444400
