[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = "plugin kdeconnect-send"
desc = "Send selected files via KDE Connect"

prepend_keymap = [
  { on = [ "<C-w>" ], run = [ 'shell --orphan "bash -c \"pkill swaybag; swaybg -i %s -m fill\""'] },
]
