layerrule = blur on, animation slide top, ignore_alpha 0, match:namespace waybar
layerrule = blur on, ignore_alpha 0, match:namespace rofi
layerrule = blur on, ignore_alpha 0, match:namespace quickshell
layerrule = blur on, animation slide right, ignore_alpha 0, match:namespace notifications
layerrule = blur on, ignore_alpha 0, match:namespace logout_dialog

windowrule {
    name = Picture-in-Picture
    match:title = ^(Picture-in-Picture)$
    float = on
    no_initial_focus = on
    move = 1420 790
    opacity = 1.0
    pin = on
    keep_aspect_ratio = on
    size = (monitor_w*0.25) (monitor_h*0.25)
}
